# Generated by Django 4.2.16 on 2025-01-11 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('cat', '猫'), ('dog', '狗')], max_length=20)),
                ('sub_type', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(choices=[('beijing', '北京'), ('shanghai', '上海'), ('guangzhou', '广州'), ('shenzhen', '深圳'), ('chengdu', '成都'), ('hangzhou', '杭州'), ('nanjing', '南京'), ('wuhan', '武汉'), ('xi_an', '西安'), ('chongqing', '重庆'), ('others', '其它')], max_length=20)),
                ('health_status', models.CharField(choices=[('healthy', '健康'), ('ill', '有病'), ('recovering', '康复中')], max_length=20)),
                ('is_stray', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('black', '黑色'), ('white', '白色'), ('brown', '棕色'), ('gray', '灰色'), ('orange', '橙色'), ('spotted', '斑点'), ('striped', '条纹')], max_length=20)),
                ('size', models.CharField(choices=[('small', '小型'), ('medium', '中型'), ('large', '大型')], max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pets/')),
                ('is_adopted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_extend')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='默认申请理由')),
                ('contact', models.CharField(default='默认联系方式', max_length=15)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('pet_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inform.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
